name: QBR Weekly Update
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
    reporter:
        runs-on: ubuntu-latest
        name: QBR Weekly Update
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Grab newest QBR data from ESPN
            run: python ./qb_scrapr.py
          - name: Push last_updated file
            uses: test-room-7/action-update-file@v1.5.0
            with:
              file-path: composite.csv
              commit-msg: "Updated QBR composite CSV after latest bot run."
              github-token: ${{ secrets.GITHUB_TOKEN }}
